FROM registry.ci.openshift.org/open-cluster-management/builder:go1.15-linux-amd64 AS builder

WORKDIR /go/src/github.com/open-cluster-management/search-collector
COPY . .
RUN CGO_ENABLED=0 GOGC=25 go build -trimpath -o main main.go


FROM scratch
WORKDIR /opt/app/
COPY --from=builder /go/src/github.com/open-cluster-management/search-collector/main ./main

USER 1001
ENTRYPOINT ["/opt/app/main"]