apiVersion: v1
kind: ConfigMap
metadata:
  name: search-collector-config
  namespace: open-cluster-management
data: 
  AllowedResources: |-
    - apiGroups: 
        - "*"
      resources: 
        - services
        - pods 
        - alertmanager
    - apiGroups:
        - open-cluster-management.io
        - tuned.openshift.io
      resources:
        - "*"
  DeniedResources: |-
    - apiGroups:
        - "*"
      resources:
        - secrets
    - apiGroups:
        - open-cluster-management.io
      resources:
        - policies
        - iampolicies
        - certificatepolicies
