apiVersion: v1
kind: ConfigMap
metadata:
  name: search-collector-config
  namespace: open-cluster-management
data: 
  AllowedResources: |-
    - apiGroups: 
        - "*"
      resources: 
        - ClusterOperator
        - clusteroperators