apiVersion: v1
kind: ConfigMap
metadata:
  name: search-collector-config
  namespace: open-cluster-management
data: 
  DeniedResources: |-
    - apiGroups:
      - "*"
      resources:
      - secrets
      - configmaps
    - apiGroups:
      - ""
      resources:
      - namespaces
    - apiGroups:
        - storage.k8s.io
      resources:
        - volumeattachments
        - volumesnapshots
    - apiGroups:
        - apps.open-cluster-management.io
      resources:
        - "*"