apiVersion: v1
kind: ConfigMap
metadata:
  name: search-collector-config
  namespace: open-cluster-management
data: 
  AllowedResources: |-
    - apiGroups: 
        - "apps.open-cluster-management.io"
      resources: 
        - channels
    - apiGroups:
        - "*"
      resources:
        - pods
        - deployments
        - subscriptions
  DeniedResources: |-
    - apiGroups:
        - "*"
      resources:
        - secrets
    - apiGroups:
        - "search.open-cluster-management.io"
      resources:
        - searches
