apiVersion: search.open-cluster-management.io/v1alpha1
kind: CollectionConfig
metadata:
  name: collection-config
  namespace: open-cluster-management
spec:
  collectFields:
    - apiGroup: ""
      kind: "Pod"
      fields:
        - name: "dnsPolicy"
          jsonPath: "{.spec.dnsPolicy}"
        - name: "enableServiceLinks"
          jsonPath: "{.spec.enableServiceLinks}"
    - apiGroup: "search.open-cluster-management.io"
      kind: "Search"
      fields:
        - name: "searchPGStorage"
          jsonPath: "{.spec.dbStorage.size}"
          type: "DataTypeBytes"
      collectAnnotations: true
      collectConditions: true
      collectAdditionalPrinterColumnsPriority: 0
  collectNamespaces:
    namespaceSelector:
      include:
        - "open-cluster-management"
      exclude:
        - "closed-cluster-management"
      matchExpressions: []
      matchLabels: {}
  allowedResources:
    - apiGroups:
        - "*"
      resources:
        - "*"
  deniedResources:
    - apiGroups:
        - "coordination.k8s.io"
      resources:
        - "leases"
