apiVersion: search.open-cluster-management.io/v1alpha1
kind: SearchCollectorCustomizableConfig
metadata:
  name: search-collector-configurable-collection
  namespace: open-cluster-management
spec:
  collectFields:
    - apiGroup: ""
      kind: "Pod"
      fields:
        - name: "dnsPolicy"
          jsonPath: "{.spec.dnsPolicy}"
        - name: "enableServiceLinks"
          jsonPath: "{.spec.enableServiceLinks}"
      inNamespace:
        - "*open-cluster-management*"
      notInNamespace:
        - "openshift-cnv"
        - "default"
    - apiGroup: "search.open-cluster-management.io"
      kind: "Search"
      fields:
        - name: "searchPGStorage"
          jsonPath: "{.spec.dbStorage.size}"
          type: "DataTypeBytes"
      collectAnnotations: true
      collectConditions: true
      namespace: "open-cluster-management"
      collectAdditionalPrinterColumnsPriority: 0
  allowedResources:
    - apiGroups:
        - "*"
      resources:
        - "*"
  deniedResources:
    - apiGroups:
        - "coordination.k8s.io"
      resources:
        - "leases"
